const fs = require('fs/promises');
const path = require('path');

async function generateThemes() {
  const revealPackageJsonPath = require.resolve('reveal.js/package.json');
  const revealPackageDir = path.dirname(revealPackageJsonPath);
  const themeDir = path.join(revealPackageDir, 'dist', 'theme');

  const destDir = path.join(process.cwd(), 'public', 'themes');
  await fs.mkdir(destDir, { recursive: true });

  const files = await fs.readdir(themeDir);
  const cssFiles = files
    .filter((file) => file.endsWith('.css'))
    .filter((file) => !file.includes('white_contrast_compact_verbatim_headers'));

  await Promise.all(
    cssFiles.map((file) =>
      fs.copyFile(path.join(themeDir, file), path.join(destDir, file))
    )
  );

  const content = `// This file is generated by scripts/generate-themes.js\nexport const themes = ${JSON.stringify(cssFiles, null, 2)};\n`;
  await fs.writeFile(path.join(process.cwd(), 'src', 'lib', 'themes.ts'), content);
  console.log('Generated themes:', cssFiles);
}

module.exports = { generateThemes };

if (require.main === module) {
  generateThemes().catch((err) => {
    console.error('Failed to generate themes', err);
    process.exit(1);
  });
}
