// scripts/themes-loader.js
const fs = require("fs");
const path = require("path");

module.exports = function themesLoader() {
  this.cacheable && this.cacheable();

  let themeDir;
  try {
    const revealPackageJsonPath = require.resolve("reveal.js/package.json");
    const revealPackageDir = path.dirname(revealPackageJsonPath);
    themeDir = path.join(revealPackageDir, "dist", "theme");

    this.addContextDependency(themeDir);

    const files = fs.readdirSync(themeDir);
    const cssFiles = files
      .filter((file) => file.endsWith(".css"))
      .filter((file) => !file.includes("white_contrast_compact_verbatim_headers"));

    console.log("✅ [themes-loader] Found themes:", cssFiles);

    if (cssFiles.length === 0) {
      throw new Error("No theme files were found in the reveal.js theme directory.");
    }

    const content = `
// This module is generated by scripts/themes-loader.js
export const themes = ${JSON.stringify(cssFiles, null, 2)};
`;
    return content;
  } catch (error) {
    const errorMessage = `
================================================================
💥 ERROR IN THEME LOADER 💥
================================================================
Failed to load reveal.js themes.
Reason: ${error.message}
Attempted to read from directory: ${themeDir || "Path could not be determined."}
Please ensure 'reveal.js' is installed correctly.
================================================================
`;
    // Log directly to the console, which is more visible than emitError
    console.error(errorMessage);
    this.emitError(error); // Keep emitting for the build tool

    // Return an empty array to prevent further build errors, but the log is our primary signal
    return `export const themes = [];`;
  }
};
